default_project
      7.1       : AquaCrop Version (August 2023)
      1         : Year number of cultivation (Seeding/planting year)
  33329         : First day of simulation period   
  33496         : Last day of simulation period
  33359         : First day of cropping period 
  33496         : Last day of cropping period 
-- 1. Climate (CLI) file
   default_project.CLI
   'C:/Users/Aleksei/PycharmProjects/AgroDT_AquaCrop_calibration/aquacrop/main/projects/default_project\DATA/'
   1.1 Temperature (Tnx or TMP) file
   default_project.Tnx
   'C:/Users/Aleksei/PycharmProjects/AgroDT_AquaCrop_calibration/aquacrop/main/projects/default_project\DATA/'
   1.2 Reference ET (ETo) file
   default_project.ETo
   'C:/Users/Aleksei/PycharmProjects/AgroDT_AquaCrop_calibration/aquacrop/main/projects/default_project\DATA/'
   1.3 Rain (PLU) file
   default_project.PLU
   'C:/Users/Aleksei/PycharmProjects/AgroDT_AquaCrop_calibration/aquacrop/main/projects/default_project\DATA/'
   1.4 Atmospheric CO2 concentration (CO2) file
   MaunaLoa.CO2
   'C:/Users/Aleksei/PycharmProjects/AgroDT_AquaCrop_calibration/aquacrop/main/projects/default_project\SIMUL/'
-- 2. Calendar (CAL) file
   default_project.CAL
   'C:/Users/Aleksei/PycharmProjects/AgroDT_AquaCrop_calibration/aquacrop/main/projects/default_project\DATA/'
-- 3. Crop (CRO) file
   default_project_fertility_stress_default_project_Wheat.CRO
   'C:/Users/Aleksei/PycharmProjects/AgroDT_AquaCrop_calibration/aquacrop/main/projects/default_project\DATA/'
-- 4. Irrigation management (IRR) file
   (None)
   (None)
-- 5. Field management (MAN) file
   default_project.MAN
   'C:/Users/Aleksei/PycharmProjects/AgroDT_AquaCrop_calibration/aquacrop/main/projects/default_project\DATA/'
-- 6. Soil profile (SOL) file
   default_project.SOL
   'C:/Users/Aleksei/PycharmProjects/AgroDT_AquaCrop_calibration/aquacrop/main/projects/default_project\DATA/'
-- 7. Groundwater table (GWT) file
   default_project.GWT
   'C:/Users/Aleksei/PycharmProjects/AgroDT_AquaCrop_calibration/aquacrop/main/projects/default_project\DATA/'
-- 8. Initial conditions (SW0) file
   default_project.SW0
   'C:/Users/Aleksei/PycharmProjects/AgroDT_AquaCrop_calibration/aquacrop/main/projects/default_project\DATA/'
-- 9. Off-season conditions (OFF) file
   (None)
   (None)
-- 10. Field data (OBS) file
   (None)
   (None)
